#!/usr/bin/env python3
"""Write mobile/.env with LAN IP for Expo and the API client (fixes Windows 127.0.0.1)."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from host_util import lan_ip  # noqa: E402

MOBILE_ENV = ROOT / "mobile" / ".env"


def main() -> None:
    ip = lan_ip()
    api_base = f"http://{ip}:5000"
    content = (
        f"# Auto-generated by make mobile — do not commit\n"
        f"EXPO_PUBLIC_API_BASE={api_base}\n"
        f"REACT_NATIVE_PACKAGER_HOSTNAME={ip}\n"
    )
    MOBILE_ENV.write_text(content, encoding="utf-8")
    print(f"Wrote {MOBILE_ENV}")
    print(f"  EXPO_PUBLIC_API_BASE={api_base}")
    print(f"  REACT_NATIVE_PACKAGER_HOSTNAME={ip}")
    if ip.startswith("127."):
        print(
            "WARN: Could not detect LAN IP — set API URL manually in app Settings.",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
